# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

State.create(name: "Aguascalientes")
State.create(name: "Baja California")
State.create(name: "Baja California Sur")
State.create(name: "Campeche")
State.create(name: "Chiapas")
State.create(name: "Mexico City")
State.create(name: "Chihuahua")
State.create(name: "Coahuila")
State.create(name: "Colima")
State.create(name: "Durango")
State.create(name: "Guanajuato")
State.create(name: "Guerrero")
State.create(name: "Hidalgo")
State.create(name: "Jalisco")
State.create(name: "Mexico")
State.create(name: "Michoacán")
State.create(name: "Morelos")
State.create(name: "Nayarit")
State.create(name: "Nuevo León")
State.create(name: "Oaxaca")
State.create(name: "Puebla")
State.create(name: "Querétaro")
State.create(name: "Quintana Roo")
State.create(name: "San Luis Potosí")
State.create(name: "Sinaloa")
State.create(name: "Sonora")
State.create(name: "Tabasco")
State.create(name: "Tamaulipas")
State.create(name: "Tlaxcala")
State.create(name: "Veracruz")
State.create(name: "Yucatán")
State.create(name: "Zacatecas")